### ISSUE TITLE
[FEATURE]: Creating Interface Setting file to customize the Background's transparency

### ISSUE THREAD

**Issue by Wuerfelhusten** [MissCorruption/QuickLootIE#34]
### Feature Title

ini-file with background transparency settings

### Motivation

This is something I would implement in UI patches myself. But it would be nicer if the option were also available to "Vanilla SkyUI" players.

**Comment by AtomCrafty** [comment]
With the latest version we have introduced two MCM options that allow players to change the opacity of the loot menu. One applies when the container still has items in it and the other one is used when it's empty. That opacity setting is applied to all visual components except for the button bar, since that should always be visible.

Does that cover your suggestion or are you saying that players should be able to change the background opacity independently of the remaining elements?

**Comment by Wuerfelhusten** [comment]
Yes. That covers everything. But one question. Will the MCM support MCM Helper (MCM Settings saved in an ini file)?

I am thinking from a patch curator perspective. As example Untarnished UI: Uses transparency. But I would not like to add transparency in the menu itself AND in the MCM. The best option would be to use a non transparent background and pack MCM Settings with the mod. (As far as I can tell)

**Comment by AtomCrafty** [comment]
The MCM has an option to import and export your settings profile to a json file. When the MCM is initialized for the first time for a new character, settings are loaded from `SKSE/Plugins/QuickLootIE/Profiles/MCMConfig.json` if that file is present. However that wouldn't happen when a new skin is installed mid-game.

**Comment by Wuerfelhusten** [comment]
hmmm, okay, that's absolutely fine for me.

**Comment by MissCorruption** [comment]
I assume this can be closed?

**Comment by Wuerfelhusten** [comment]
Yes, it can
