### ISSUE TITLE
[Bug]: "Disable Quickloot for animals" setting doesn't function

### ISSUE THREAD

**Issue by Aethozoid** [MissCorruption/QuickLootIE#43]
### What happened?

In the mod's MCM, clicking the "Disable Quickloot for animals" option does not change the check icon, which remains unchecked. The setting does not function in-game. This was tested with a minimal load order using Vortex.

(This was tested with mod version 1.2.0. This version was not in the selectable version list in the bug report page in GitHub.)

**Installed Mods**
- All in one Address Library (Anniversary Edition)
- QuickLootIE - A QuickLoot EE Fork
- Skyrim Configuration Menu
- Skyrim Script Extender (SKSE64)
- SkyUI_5_2_SE

### Version

1.1.0

### What Skyrim version are you using?

1.6.1170.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
The entire MCM has been rewritten from scratch for 2.0.0. This particular toggle has been replaced by the "Hunting mods support" setting and works as intended on the latest version. 
![image](https://github.com/user-attachments/assets/971b56a7-1fdb-4f14-895d-8eb87581b532)

**Comment by Aethozoid** [comment]
Thanks! Though, the DLL file doesn't load correctly and doesn't seem to work at all in-game, although the MCM shows up just fine.

**Comment by AtomCrafty** [comment]
Huh, that is strange. First time I hear about loading issues on 1170. Can you upload your skse64 and QuickLootIE logs?

**Comment by Aethozoid** [comment]
I'm not super well-versed in dealing with logs. I looked in "Documents\My Games\ SKyrim Special Edition\SKSE" and couldn't find any files with the "QuickLootIE" name, but I did find what seemed like relevant info in this SKSE log. If you could point me in the right direction to find the exact logs you're looking for, I'll try to retrieve them.
[skse64.log](https://github.com/user-attachments/files/16431281/skse64.log)

**Comment by AtomCrafty** [comment]
Thanks, that is the correct SKSE log. The QuickLootIE log probably doesn't exist for you because the dll fails to load in the first place. The log confirms that. This could be due to a missing dependency on your end, likely the [VC++ Redistributables](https://aka.ms/vs/17/release/vc_redist.x64.exe).

You can check for missing dependencies with [this tool](https://github.com/lucasg/Dependencies/releases/tag/v1.11.1). Extract `Dependencies_x64_Release.zip` to a temporary folder, run `DependenciesGui.exe` and drag `QuickLootIE.dll` into the window that opens. If any of the entries in the top left panel show a warning you are missing a system dll.

**Comment by Aethozoid** [comment]
This is very strange. Using the DependenciesGUI program, I've identified the dll files I'm missing. However, even after a decent amount of Google-searching, I've found no reliable, safe way to get these files.
I've executed the VC Redistributable file from the link you posted multiple times now. The first few times I've not had an "install" option, only the "repair" option, so I've had it installed already. Both methods of repairing and uninstalling/reinstalling did not seem to install these files. - the missing dlls shown in DependenciesGUI.exe did not change, nor did the QuickLootIE error go away. I've also tried a few other versions of the VC redistributable off the official Microsoft site, but those have given me messages that they are outdated, so I didn't bother.
Even after doing Google searches on the dll files and performing some suggested methods, like downloading Visual Studio 2022 and some of its optional C++ packages, I'm still at a loss as to how to safely procure these files. I've found results to download the exact files from DLL-Files.com, but from what I've seen, there's no guarantee that the files downloaded from the site will be safe to use.
This issue may likely be outside the realm of this mod and may be an issue with my own Windows installation, so I wouldn't blame you for not looking into this issue further, but I thought I would lay everything I'm experiencing out just in case there's a way around it all.

![image](https://github.com/user-attachments/assets/77d0357d-cf78-46b8-b03b-8eb8ab1402d6)

**Comment by AtomCrafty** [comment]
Oh, I see what's wrong. It's not an issue on your end.

The canary build on GitHub is built in the debug configuration, so it requires the debug version of the VC++ libraries (denoted by the `D` suffix of those four DLL names). Those aren't included in the VC++ Redist packages, since they are usually only needed by developers and shipped with the VS Build Tools. None of us devs noticed it because we naturally all have the build tools installed.

@MissCorruption is there any reason why is built in `Debug`? It's fine for the nightly builds, but I think `RelWithDebInfo` would be a more useful configuration for (pre-)releases.

**Comment by MissCorruption** [comment]
The canary should now be built to work without debug redistributables. Try the latest release and report back @Aethozoid

**Comment by Aethozoid** [comment]
I just tested the release and the hunting mod setting and everything seems to work perfectly now. This is the best iteration of QuickLoot I've seen yet. Thank you!
