### ISSUE TITLE
[BUG]: Skyrim Souls RE Tween Menu No Mouse Cursor Fix

### ISSUE THREAD

**Issue by Aqua-Markwin** [MissCorruption/QuickLootIE#48]
### Feature Title

Skyrim Souls RE Tween Menu No Mouse Cursor Fix

### Motivation

My motivation is that with every quickloot mod, be it RE or EE or this at the moment, when the quickloot menu is up it disables the mouse cursor in the tween menu when used with Skyrim Souls RE for un-paused menus, which is very annoying.

### Feature Description

A fix for the mouse cursor being disabled in the tween menu while the quickloot menu is up, while used in conjunction with Skyrim Souls RE. I'm unsure if the issue is fixable on this mod's end but I hope it is.

### Additional Context

I'm unsure if I should have maybe submitted this as a bug instead, but my gut tells me that because it deals with another mod that it should probably be considered a feature if it is considered.

**Comment by AtomCrafty** [comment]
Just installed Skyrim Souls RE to test this and opening the tween menu while the loot menu is open doesn't just hide the cursor, it completely softlocks the game for me since it makes it impossible to interact with or close the tween menu.

If I force close the loot menu while the tween menu is open, the issue doesn't occur. The main question is why it even shows in the first place. The loot menu is already supposed to be suppressed when any full screen menu is open. My best guess at this point is that Skyrim Souls RE messes with the menu flags so it is no longer recognized as having a higher priority than QuickLoot.

**Comment by MissCorruption** [comment]
This is likely something that needs to be fixed on Skyrim Souls' side, what happens when you disable the Tween Menu in Souls' config?

**Comment by AtomCrafty** [comment]
It's not just the tween menu that's broken for me. Opening the container menu has the same issue. It looks to me like SSRE changes the menu flags and priority, which messes with QL's ability to detect a higher priority menu being open. I'm currently refactoring that exact part of the QL codebase, to I'll try to see whether I can fix this.

**Comment by Aqua-Markwin** [comment]
> This is likely something that needs to be fixed on Skyrim Souls' side, what happens when you disable the Tween Menu in Souls' config?

It still happens with every menu set to false in Skyrim Souls' ini.

**Comment by AtomCrafty** [comment]
Okay, I think I know why this is happening. Usually, the loot menu would be disabled in these scenarios because `RE::UI::GetSingleton()->GameIsPaused()` returns true, but with Skyrim Souls installed the game doesn't get paused while in these menus.

We have a system in place that allows disabling the loot menu while certain blacklisted menus are open, which currently is only used for the dialogue menu since that is the only menu that normally doesn't pause the game. We could add all menus to that blacklist, but it doesn't exactly feel like a good solution. Especially since it wouldn't include menus added by other mods.

I've written some logic that manually walks the menu stack and checks if any menus are open that don't have the `kAlwaysOpen` flag set. Initial tests are promising, but we'll need to make sure this doesn't have unintended side effects.

**Comment by MissCorruption** [comment]
Fixed by #40
