### ISSUE TITLE
[Bug]: Text wrong color

### ISSUE THREAD

**Issue by Neutral9** [MissCorruption/QuickLootIE#54]
### What happened?

When opening the container using Quick Loot IE The text color is white, although it should be warm yellow as in Dear Diary Dark Mode (Warm), Otherwise works fine, also for reference I use komegaki - Kome's Inventory Tweaks and all his mods

### Version

2.0.0

### What Skyrim version are you using?

1.5.97

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AtomCrafty** [comment]
Are you using the official DDDM reskin from our Nexus page or a third party patch?

**Comment by Neutral9** [comment]
I use official DDDM reskin

**Comment by AtomCrafty** [comment]
Hmm, I use that skin myself and everything has the warm color for me.

There are only two ways for an item's text color to change from the default color.
1. If Completionist is installed and the item is assigned a color by that (green or blue by default).
2. If i4 is installed and any rule overwrites the text color for the item.

Could you confirm whether the issue still occurs when you disable i4 and all mods that depend on it?

**Comment by Neutral9** [comment]
I found the problem, on the path interface\skyui is config.txt there is a line colors.stolen.enabled = 0xffcc99 this config was overwritten by Kome's Inventory Tweaks mod and there was prescribed white color instead of yellow, I edited and that's it.

**Comment by LeavingUndad** [comment]
Sorry, I suspect it's my own fault due to an improper installation of KIT, but I've just installed it and all the vegetables in the QuickLoot IE menu have an icon of a health potion instead of the supposed leek icon:

[url=https://postimg.cc/BjFybrjr][img]https://i.postimg.cc/htZqygct/For-Quick-Loot-IE-KIT-s-Vegs-01.png[/img][/url]
[url=https://postimg.cc/WD6H606S][img]https://i.postimg.cc/Zq1zmc9k/For-Quick-Loot-IE-KIT-s-Vegs-02.png[/img][/url]

@[Neutral9](https://github.com/Neutral9) Since you also use KIT, can you confirm/refute it in your game?

@All Any idea what may cause it?
Thanks.

**Comment by MissCorruption** [comment]
I just tested KIT v2 and it worked fine for me, fwiw.

**Comment by Komegaki** [comment]
@LeavingUndad This issue will be fixed if you update to the (WIP) KIT v2.0 Beta (99% sure).
Here's the link to the latest pre-release as of writing this (https://github.com/Komegaki/Komegaki-Inventory-Tweaks/releases/tag/V2_1.06_Beta)
Make sure to read the desc. (at least the top portion) and let us know if this fixes the problem.

**Comment by LeavingUndad** [comment]
@[Komegaki](https://github.com/Komegaki) Thank you a lot for the reply and for your mod, of course! I didn't know that your KIT mod also has Pre-release versions on github. I've downloaded and installed the latest V2_1.06_Beta from there and can confirm that the mentioned issue I experienced previously with the stable v.1.21 of your mod has been fixed with it indeed. Special thanks for that in particular!

Btw I'm an old gamer and still do not trust MO2 and prefer to use Wrye Bash (WB) to install the mods. Unfortunately WB gave me an error when I tried to install "Kome.Inventory.Tweaks.KIT.zip" with its FOMOD wizard. So I had to convert the archive into a BAIN-friendly format. I hope I've done it correctly (what a tedious work btw!).

Also I've detected a typo in line 50 of the "Kome.Inventory.Tweaks.KIT.Patches.zip\Kome's Inventory Tweaks (KIT) - Patches\Patch - SLADD Config\SKSE\Plugins\SLAAD_Config.toml" file:

TomeSchool_05_Restoration = "Resotration "
should be
TomeSchool_05_Restoration = "Restoration "

There is also a typo in the name of the "Patch - SLADD Config" folder inside the "Kome.Inventory.Tweaks.KIT.Patches.zip" archive, as you can see (SLADD instead of SLAAD), the same typo is in the FOMOD wizard itself as well. [I've also reported the typos on the Nexus page of your mod](https://www.nexusmods.com/skyrimspecialedition/mods/116713?tab=posts) under my Nibenon76 account (the stable vesion also has these typos) and asked you a question there about the SLAAD_Config.toml customization.

Sorry for the long post, which has become mostly not related to QuickLoot IE.

**Comment by Komegaki** [comment]
@LeavingUndad All good! Glad the v2.0 Beta fixed your problem haha.
TY for letting me know about these typos, I made notes and will fix those before the next v2.0 Beta update!
As for the SLAAD_Config.toml customization, the .toml file was edited by a friend who uses SLAAD, I don't think editing it would hurt anything though!
